export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';

export const PLANNER_ADD_RECIPE_TO_PLAN = 'PLANNER_ADD_RECIPE_TO_PLAN'; // where dynamic id is made?
export const PLANNER_REMOVE_RECIPE_FROM_PLAN = 'PLANNER_REMOVE_RECIPE_FROM_PLAN'; // where dynamic id is unmade?
export const PLANNER_CLICK_DAY = 'PLANNER_CLICK_DAY';
export const PLANNER_ADD_RECIPE_TO_DAY = 'PLANNER_ADD_RECIPE_TO_DAY';
export const PLANNER_REMOVE_RECIPE_FROM_DAY = 'PLANNER_REMOVE_RECIPE_FROM_DAY';
export const PLANNER_REORDER_RECIPE_IN_DAY = 'PLANNER_REORDER_RECIPE_IN_DAY';
//export const PLANNER_ = 'PLANNER_';