export const SAMPLE = 'SAMPLE';

export const GET_INGREDIENTS_START = 'GET_INGREDIENTS_START';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';