export const USER_CREATE_NEW_PRIVATE_INGREDIENT = 'USER_CREATE_NEW_PRIVATE_INGREDIENT';
export const USER_CREATE_NEW_PRIVATE_INGREDIENT_SUCCEEDED = 'USER_CREATE_NEW_PRIVATE_INGREDIENT_SUCCEEDED';
export const USER_CREATE_NEW_PRIVATE_INGREDIENT_FAILED = 'USER_CREATE_NEW_PRIVATE_INGREDIENT_FAILED';

export const USER_EDIT_PRIVATE_INGREDIENT = 'USER_EDIT_PRIVATE_INGREDIENT';
export const USER_EDIT_PRIVATE_INGREDIENT_SUCCEEDED = 'USER_EDIT_PRIVATE_INGREDIENT_SUCCEEDED';
export const USER_EDIT_PRIVATE_INGREDIENT_FAILED = 'USER_EDIT_PRIVATE_INGREDIENT_FAILED';

export const USER_DELETE_PRIVATE_INGREDIENT = 'USER_DELETE_PRIVATE_INGREDIENT';
export const USER_DELETE_PRIVATE_INGREDIENT_SUCCEEDED = 'USER_DELETE_PRIVATE_INGREDIENT_SUCCEEDED';
export const USER_DELETE_PRIVATE_INGREDIENT_FAILED = 'USER_DELETE_PRIVATE_INGREDIENT_FAILED';

