
    /* eslint-disable */
    /* tslint:disable */
    
    // generated by react-imported-component, DO NOT EDIT     
    import {assignImportedComponents} from 'react-imported-component/macro';
    undefined    
    
    // all your imports are defined here
    // all, even the ones you tried to hide in comments (that's the cost of making a very fast parser)
    // to remove any import from here
    // 1) use magic comment `import(/* client-side */ './myFile')` - and it will disappear
    // 2) use file filter to ignore specific locations (refer to the README - https://github.com/theKashey/react-imported-component/#server-side-auto-import)
    // 3) use .imported.js to control this table generation (refer to the README - https://github.com/theKashey/react-imported-component/#-imported-js)
    
    const applicationImports = assignImportedComponents([
      [() => import('./pages/Content/Content'), '', './src/pages/Content/Content', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Equipment/Equipment'), '', './src/pages/Equipment/Equipment', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Equipments/Equipments'), '', './src/pages/Equipments/Equipments', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Ingredient/Ingredient'), '', './src/pages/Ingredient/Ingredient', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Ingredients/Ingredients'), '', './src/pages/Ingredients/Ingredients', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Login/Login'), '', './src/pages/Login/Login', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Navigation/Navigation'), '', './src/pages/Navigation/Navigation', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/NewContent/NewContent'), '', './src/pages/NewContent/NewContent', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/NewEquipment/NewEquipment'), '', './src/pages/NewEquipment/NewEquipment', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/NewIngredient/NewIngredient'), '', './src/pages/NewIngredient/NewIngredient', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/NewRecipe/NewRecipe'), '', './src/pages/NewRecipe/NewRecipe', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Profile/Profile'), '', './src/pages/Profile/Profile', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Recipe/Recipe'), '', './src/pages/Recipe/Recipe', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Recipes/Recipes'), '', './src/pages/Recipes/Recipes', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/Register/Register'), '', './src/pages/Register/Register', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/staff/Dashboard/Dashboard'), '', './src/pages/staff/Dashboard/Dashboard', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/user/Dashboard/Dashboard'), '', './src/pages/user/Dashboard/Dashboard', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/user/Friends/Friends'), '', './src/pages/user/Friends/Friends', false] /* from ./src/routing/Routes.tsx */,
      [() => import('./pages/user/Messenger/Messenger'), '', './src/pages/user/Messenger/Messenger', false] /* from ./src/pages/user/Messenger/MessengerPage.tsx */,
      [() => import('./pages/user/Messenger/MessengerPage'), '', './src/pages/user/Messenger/MessengerPage', false] /* from ./src/routing/Routes.tsx */,
      //[() => import('./pages/user/Messenger/MobileMessengerToggle'), '', './src/pages/user/Messenger/MobileMessengerToggle', false] /* from ./src/pages/user/Messenger/MessengerPage.tsx */,
      //[() => import('./pages/user/NewPlan/MobileNewPlanToggle'), '', './src/pages/user/NewPlan/MobileNewPlanToggle', false] /* from ./src/pages/user/NewPlan/NewPlanPage.tsx */,
      [() => import('./pages/user/NewPlan/NewPlan'), '', './src/pages/user/NewPlan/NewPlan', false] /* from ./src/pages/user/NewPlan/NewPlanPage.tsx */,
      [() => import('./pages/user/NewPlan/NewPlanPage'), '', './src/pages/user/NewPlan/NewPlanPage', false] /* from ./src/routing/Routes.tsx */,
      //[() => import('./pages/user/Plan/MobilePlanToggle'), '', './src/pages/user/Plan/MobilePlanToggle', false] /* from ./src/pages/user/Plan/PlanPage.tsx */,
      [() => import('./pages/user/Plan/Plan'), '', './src/pages/user/Plan/Plan', false] /* from ./src/pages/user/Plan/PlanPage.tsx */,
      [() => import('./pages/user/Plan/PlanPage'), '', './src/pages/user/Plan/PlanPage', false] /* from ./src/routing/Routes.tsx */,
    ]);
    
    export default applicationImports;
    
    // @ts-ignore
    if (module.hot) {
       // these imports would make this module a parent for the imported modules.
       // but this is just a helper - so ignore(and accept!) all updates
       
       // @ts-ignore
       module.hot.accept(() => null);
    }    
    